#!/bin/bash
host="127.0.0.1"
port="5432"
user="postgres"
password="yourpassword"


function check_postgres {
    psql -h $host -p $port -U $user -c "SELECT 1;" >/dev/null 2>&1
    if [ $? -eq 0 ]; then
        echo "PostgreSQL is running!"
    else
        echo "PostgreSQL is not running!"
    fi
}


check_postgres
